<a href="https://colab.research.google.com/github/rudipop/Rudi_Aulas_Python/blob/main/Python_Aula2_parte4_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [17]:
r1 = np.ones((4,3,2))


In [6]:
r1

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
r1.shape

(4, 3, 2)

In [8]:
r0 = np.zeros((4,3,2))

In [10]:
r0

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
r_random = np.random.random((4,3,2))

In [14]:
r_random

array([[[0.60600164, 0.6760379 ],
        [0.12542895, 0.7130408 ],
        [0.70947783, 0.3078966 ]],

       [[0.29419573, 0.8651718 ],
        [0.85214138, 0.77792974],
        [0.85240067, 0.72495019]],

       [[0.88624051, 0.48268322],
        [0.96123841, 0.46030866],
        [0.58277417, 0.8020031 ]],

       [[0.1646766 , 0.01545605],
        [0.16611249, 0.0689429 ],
        [0.0706828 , 0.52758601]]])

In [19]:
r1 + r_random

array([[[1.60600164, 1.6760379 ],
        [1.12542895, 1.7130408 ],
        [1.70947783, 1.3078966 ]],

       [[1.29419573, 1.8651718 ],
        [1.85214138, 1.77792974],
        [1.85240067, 1.72495019]],

       [[1.88624051, 1.48268322],
        [1.96123841, 1.46030866],
        [1.58277417, 1.8020031 ]],

       [[1.1646766 , 1.01545605],
        [1.16611249, 1.0689429 ],
        [1.0706828 , 1.52758601]]])

Criar array fornecendo os valores


In [26]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
x.shape

(2, 4)

In [30]:
x.size #numero de elementos

8

In [32]:
x.ndim # numero de dimensoes


2

In [33]:
x.dtype

dtype('int64')

é do tipo inteiro

In [35]:
x.sum() # soma de todos os elementos

36

In [37]:
x.max()

8

In [40]:
x.min()

1

acessar elementos do arrays

In [41]:
# aceessar o primeiro elemento
x[0,0]

1

In [44]:
x[1,1] #segunda linha e segunda coluna

6

In [46]:
# multiplos elementos
x[0,1:3]# observar que é inclusive:exclusive, aqui fica a primeira linha, e o elementos da coluna 2 e 3

array([2, 3])

Operações com matrizes


In [48]:
2*x

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [51]:
a = np.array([[1,2],[4,5]])
b = np.array([[10,20],[30,40]])

print(a)
print(b)


[[1 2]
 [4 5]]
[[10 20]
 [30 40]]


In [53]:
2*a

array([[ 2,  4],
       [ 8, 10]])

In [55]:
a+2

array([[3, 4],
       [6, 7]])

In [57]:
#multiplicação de matrizes, observar que o num de colunas da primeira deve ser igual ao num de linhas da segunda matriz
a.dot(b)

array([[ 70, 100],
       [190, 280]])